//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyName.ProductName.Modules.Forum.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelErrorResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelErrorResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyName.ProductName.Modules.Forum.Website.ModelErrorResourceStrings", typeof(ModelErrorResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子结贴给分({0})与帖子总分数({1})不一致！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_CloseThreadTotalMarksNotMatch {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_CloseThreadTota" +
                        "lMarksNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版块组名称({0})重复！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateGroupSubject {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateGroupS" +
                        "ubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称({0})重复！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateRoleName {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateRoleNa" +
                        "me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版块名称({0})重复！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateSectionSubject {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_DuplicateSectio" +
                        "nSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版块组({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_GroupNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_GroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子回复的作者({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_PostAuthorNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_PostAuthorNotEx" +
                        "ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_RoleNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版块({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_SectionNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_SectionNotExist" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子作者({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadAuthorNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadAuthorNot" +
                        "Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的积分不足，您目前有积分{0}, 但实际需要积分({1}).
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadAuthorNotHaveEnoughMarks {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadAuthorNot" +
                        "HaveEnoughMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子所属版块({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadSectionNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_ThreadSectionNo" +
                        "tExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户({0})不存在！.
        /// </summary>
        internal static string CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_UserNotExist {
            get {
                return ResourceManager.GetString("CompanyName_ProductName_Modules_Forum_Models_ForumValidationError_UserNotExist", resourceCulture);
            }
        }
    }
}
